export const SORT_PROS_LIST_WITH_DRAG = 'SORT_PROS_LIST_WITH_DRAG';
export const SORT_CONS_LIST_WITH_DRAG = 'SORT_CONS_LIST_WITH_DRAG';

export const CREATE_PROS_ITEM = 'CREATE_PROS_ITEM';
export const CREATE_CONS_ITEM = 'CREATE_CONS_ITEM';

export const EDIT_PROS_TITLE = 'EDIT_PROS_TITLE';
export const EDIT_CONS_TITLE = 'EDIT_CONS_TITLE';
